pipeline{
    agent any
    stages{
      stage('Build'){
          steps{
          echo 'Build Stage'
          }
      }
      stage('clean'){
          steps{
          bat 'mvn clean'
          }
      }
    }
}
