pipeline{
    agent any
    stages{
      stage('Build'){
          steps{
          echo 'Build Stage'
          }
      }
      stage('test'){
          steps{
          bat 'mvn -f path/to/pom.xml mvn test'
          }
      }
    }
}
